#!/usr/bin/env bash
set -euo pipefail
# alert.sh — pillar drift alerting script
#
# Runs drift.sh and, if drift is detected, writes a findings report and
# exits non-zero for CI gate use.
#
# Usage: bash tools/pillar-fleet/alert.sh
# Returns: 0 (no drift) or 1 (drift detected)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
FINDINGS_DIR="$REPO_DIR/findings"
DRIFT_SCRIPT="$SCRIPT_DIR/drift.sh"
TIMESTAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
DATE_STAMP="$(date -u +%Y-%m-%d)"

# --- Run drift detection ----------------------------------------------------
DRIFT_OUTPUT="$("$DRIFT_SCRIPT" 2>&1)" || true
# Filter to just the WARN lines — header/footer are always printed.
WARN_LINES="$(echo "$DRIFT_OUTPUT" | grep --color=never '^WARN:' || true)"

if [ -z "$WARN_LINES" ]; then
  echo "pillar-drift OK — no drifted items (threshold from drift.sh)"
  exit 0
fi

# --- Drift detected — create findings file ----------------------------------
COUNT="$(echo "$WARN_LINES" | wc -l | tr -d ' ')"

if [ "$COUNT" -le 3 ]; then
  SEVERITY="low"
elif [ "$COUNT" -le 10 ]; then
  SEVERITY="medium"
else
  SEVERITY="high"
fi

mkdir -p "$FINDINGS_DIR"
ALERT_FILE="$FINDINGS_DIR/drift-alert-$DATE_STAMP.md"

{
  echo "# Pillar Drift Alert — $DATE_STAMP"
  echo ""
  echo "**Generated**: $TIMESTAMP"
  echo "**Drift count**: $COUNT"
  echo "**Severity**: $SEVERITY"
  echo ""
  echo "## Drift Details"
  echo ""
  echo '```'
  echo "$WARN_LINES"
  echo '```'
  echo ""
  echo "<!-- auto-generated by tools/pillar-fleet/alert.sh -->"
} > "$ALERT_FILE"

echo "pillar-drift ALERT — ${COUNT} drifted item(s) (severity: ${SEVERITY}) → ${ALERT_FILE}"
exit 1
