#!/usr/bin/env bash
#==============================================================================
# tools/pillar-fleet/persist-busy-timeout.sh — Forge DB Busy Timeout Persistence
#
# Ensures busy_timeout=5000 and journal_mode=WAL survive daemon restart
# by configuring the forge daemon connection initialization.
#
# Usage:
#   persist-busy-timeout.sh                    # Apply to default paths
#   persist-busy-timeout.sh --db ~/.forge.db   # Custom DB path
#   persist-busy-timeout.sh --check            # Verify current settings
#   persist-busy-timeout.sh --daemon-config    # Install daemon startup hook
#==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
DBS=()
DAEMON_CONFIG=false
CHECK_ONLY=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --db)          DBS+=("$2"); shift 2 ;;
        --daemon-config) DAEMON_CONFIG=true; shift ;;
        --check)       CHECK_ONLY=true; shift ;;
        --help)        head -20 "$0"; exit 0 ;;
        *)             echo "Unknown: $1"; exit 1 ;;
    esac
done

# Default DB paths if none specified
if [[ ${#DBS[@]} -eq 0 && "$CHECK_ONLY" == false ]]; then
    DBS=( "$HOME/.forge.db" )
    # Also check common locations
    for p in "$HOME/.forge/.forge.db" "$HOME/Library/Application Support/forge/forge.db"; do
        if [[ -f "$p" ]]; then
            DBS+=("$p")
        fi
    done
fi

# Persistence marker file
MARKER="$HOME/.config/forge/busy-timeout-persisted"

apply_settings() {
    local db="$1"
    if [[ ! -f "$db" ]]; then
        echo "⚠️  DB not found: $db" >&2
        return 1
    fi

    local before_busy
    local before_journal
    before_busy=$(sqlite3 "$db" "PRAGMA busy_timeout;" 2>/dev/null || echo "error")
    before_journal=$(sqlite3 "$db" "PRAGMA journal_mode;" 2>/dev/null || echo "error")

    sqlite3 "$db" "PRAGMA busy_timeout = 5000;" 2>/dev/null
    sqlite3 "$db" "PRAGMA journal_mode = wal;" 2>/dev/null

    local after_busy
    local after_journal
    after_busy=$(sqlite3 "$db" "PRAGMA busy_timeout;" 2>/dev/null || echo "error")
    after_journal=$(sqlite3 "$db" "PRAGMA journal_mode;" 2>/dev/null || echo "error")

    echo "$db: busy_timeout ${before_busy}ms → ${after_busy}ms, journal ${before_journal} → ${after_journal}" >&2
}

create_daemon_hook() {
    local daemon_dir="$HOME/.config/forge"
    mkdir -p "$daemon_dir"

    local hook_file="$daemon_dir/on_startup.sh"
    cat > "$hook_file" << 'HOOK'
#!/usr/bin/env bash
# Forge daemon startup hook — apply busy_timeout and WAL
# Auto-generated by tools/pillar-fleet/persist-busy-timeout.sh
set -euo pipefail

# Primary forge DB
if [[ -f "$HOME/.forge.db" ]]; then
    sqlite3 "$HOME/.forge.db" "PRAGMA busy_timeout = 5000;" 2>/dev/null || true
    sqlite3 "$HOME/.forge.db" "PRAGMA journal_mode = wal;" 2>/dev/null || true
fi

# Secondary paths
for p in "$HOME/.forge/.forge.db" "$HOME/Library/Application Support/forge/forge.db"; do
    if [[ -f "$p" ]]; then
        sqlite3 "$p" "PRAGMA busy_timeout = 5000;" 2>/dev/null || true
        sqlite3 "$p" "PRAGMA journal_mode = wal;" 2>/dev/null || true
    fi
done

echo "[forge-startup-hook] busy_timeout=5000 WAL applied: $(date -u +%FT%TZ)" >> "$HOME/.forge-startup-hook.log"
HOOK
    chmod +x "$hook_file"
    echo "$hook_file" >&2
    echo "Startup hook installed at $hook_file" >&2

    # Create marker
    mkdir -p "$(dirname "$MARKER")"
    date -u +%FT%TZ > "$MARKER"
    echo "Persistence marker: $MARKER" >&2
}

# --- Main ---
if [[ "$CHECK_ONLY" == true ]]; then
    echo "Checking forge DB timeout settings..." >&2
    DBS_CHECK=( "$HOME/.forge.db" "$HOME/.forge/.forge.db" "$HOME/Library/Application Support/forge/forge.db" )
    for db in "${DBS_CHECK[@]}"; do
        if [[ -f "$db" ]]; then
            busy=$(sqlite3 "$db" "PRAGMA busy_timeout;" 2>/dev/null || echo "N/A")
            journal=$(sqlite3 "$db" "PRAGMA journal_mode;" 2>/dev/null || echo "N/A")
            echo "$db: busy_timeout=${busy}ms, journal=${journal}" >&2
        fi
    done
    echo "Marker file: $(test -f "$MARKER" && cat "$MARKER" || echo 'not set')" >&2
    exit 0
fi

if [[ "$DAEMON_CONFIG" == true ]]; then
    create_daemon_hook
fi

# Apply to all DBs
for db in "${DBS[@]}"; do
    apply_settings "$db"
done

echo "Done. Changelog: busy_timeout ↔ WAL" >&2
